services:

  node-api:
    image: ghcr.io/st2f/node-vue-cicd-docker/node-api:latest
    ports:
      - "3000:80"

  frontend:
    image: ghcr.io/st2f/node-vue-cicd-docker/frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/e2e
  
  cypress:
    image: cypress/included
    working_dir: /e2e
    volumes:
       - ./frontend:/e2e
    entrypoint: cypress run --config baseUrl=http://frontend --headless --browser chrome -C cypress.config.mjs
    depends_on:
      - node-api
      - frontend
      
