name: CI/CD w/ docker
on:
  push:
    branches: main

jobs:
  build-frontend:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
        -
          context_name: ./frontend
          image_name: ghcr.io/${{ github.repository }}/frontend:latest
        -
          context_name: ./node-api
          image_name: ghcr.io/${{ github.repository }}/node-api:latest

    permissions:
      packages: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image_name }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context_name }}
          push: true
          tags: ${{ matrix.image_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

 